language: java
script: mvn clean test -Dmaven.javadoc.skip=true -Dspring.profiles.active=test -B -V
sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
notifications:
  email: false