package com.codecool.volunti.model.enums;

public enum Countries {

    Afghanistan,
    Albania,
    Algeria,
    American_Samoa,
    Andorra,
    Angola,
    Anguilla,
    Antarctica,
    Antigua_And_Barbuda,
    Argentina,
    Armenia,
    Aruba,
    Australia,
    Austria,
    Azerbaijan,

    Bahamas,
    Bahrain,
    Bangladesh,
    Barbados,
    Belarus,
    Belgium,
    Belize,
    Benin,
    Bermuda,
    Bhutan,
    Bolivia,
    Bosnia_And_Herzegovina,
    Botswana,
    Bouvet_Island,
    Brazil,
    British_Indian_Ocean_Territory,
    Brunei_Darussalam,
    Bulgaria,
    Burkina_Faso,
    Burundi,

    Cambodia,
    Cameroon,
    Canada,
    Cape_Verde,
    Cayman_Islands,
    Central_African_Republic,
    Chad,
    Chile,
    China,
    Christmas_Island,
    Cocos_Islands,
    Colombia,
    Comoros,
    Congo,
    Cook_Islands,
    Costa_Rica,
    Cote_D_ivoire,
    Croatia,
    Cuba,
    Cyprus,
    Czech_Republic,

    Denmark,
    Djibouti,
    Dominica,
    Dominican_Republic,

    East_Timor,
    Ecuador,
    Egypt,
    El_Salvador,
    Equatorial_Guinea,
    Eritrea,
    Estonia,
    Ethiopia,

    Falkland_Islands,
    Fiji,
    Finland,
    France,
    French_Guiana,
    French_Polynesia,
    French_Southern_Territories,

    Gabon,
    Gambia,
    Georgia,
    Germany,
    Ghana,
    Gibraltar,
    Greece,
    Greenland,
    Grenada,
    Guadeloupe,
    Guam,
    Guatemala,
    Guinea,
    Guinea_bissau,
    Guyana,

    Haiti,
    Heard_Island_And_Mcdonald_Islands,
    Holy_See_Vatican_City_State,
    Honduras,
    Hong_Kong,
    Hungary,

    Iceland,
    India,
    Indonesia,
    Iran,
    Iraq,
    Ireland,
    Israel,
    Italy,

    Jamaica,
    Japan,
    Jordan,

    Kazakstan,
    Kenya,
    Kiribati,
    Korea_Democratic_People_s_Republic_Of,
    Korea_Republic_Of,
    Kosovo,
    Kuwait,
    Kyrgyzstan,

    Lao_People_s_Democratic_Republic,
    Latvia,
    Lebanon,
    Lesotho,
    Liberia,
    Libyan_Arab_Jamahiriya,
    Liechtenstein,
    Lithuania,
    Luxembourg,

    Macau,
    Macedonia,
    Madagascar,
    Malawi,
    Malaysia,
    Maldives,
    Mali,
    Malta,
    Marshall_Islands,
    Martinique,
    Mauritania,
    Mauritius,
    Mayotte,
    Mexico,
    Micronesia,
    Moldova,
    Monaco,
    Mongolia,
    Montserrat,
    Montenegro,
    Morocco,
    Mozambique,
    Myanmar,

    Namibia,
    Nauru,
    Nepal,
    Netherlands,
    Netherlands_Antilles,
    New_Caledonia,
    New_Zealand,
    Nicaragua,
    Niger,
    Nigeria,
    Niue,
    Norfolk_Island,
    Northern_Mariana_Islands,
    Norway,

    Oman,

    Pakistan,
    Palau,
    Palestinian_Territory,
    Panama,
    Papua_New_Guinea,
    Paraguay,
    Peru,
    Philippines,
    Pitcairn,
    Poland,
    Portugal,
    Puerto_Rico,

    Qatar,

    Reunion,
    Romania,
    Russian_Federation,
    Rwanda,

    Saint_Helena,
    Saint_Kitts_And_Nevis,
    Saint_Lucia,
    Saint_Pierre_And_Miquelon,
    Saint_Vincent_And_The_Grenadines,
    Samoa,
    San_Marino,
    Sao_Tome_And_Principe,
    Saudi_Arabia,
    Senegal,
    Serbia,
    Seychelles,
    Sierra_Leone,
    Singapore,
    Slovakia,
    Slovenia,
    Solomon_Islands,
    Somalia,
    South_Africa,
    South_Georgia_And_The_South_Sandwich_Islands,
    Spain,
    Sri_Lanka,
    Sudan,
    Suriname,
    Svalbard_And_Jan_Mayen,
    Swaziland,
    Sweden,
    Switzerland,
    Syrian_Arab_Republic,

    Taiwan,
    Tajikistan,
    Tanzania,
    Thailand,
    Togo,
    Tokelau,
    Tonga,
    Trinidad_And_Tobago,
    Tunisia,
    Turkey,
    Turkmenistan,
    Turks_And_Caicos_Islands,
    Tuvalu,

    Uganda,
    Ukraine,
    United_Arab_Emirates,
    United_Kingdom,
    United_States,
    United_States_Minor_Outlying_Islands,
    Uruguay,
    Uzbekistan,

    Vanuatu,
    Venezuela,
    Viet_Nam,
    Virgin_Islands,

    Wallis_And_Futuna,
    Western_Sahara,

    Yemen,

    Zambia,
    Zimbabwe
}
